- name: Set charm name
  when: zuul.message is defined
  set_fact:
    charm_name: "{{ zuul.project.short_name | replace('charm-', '') }}"

- name: Process commit message
  when: zuul.message is defined
  process_commit_msg:
    commit_message: "{{ zuul.message }}"
    files:
      - "{{ zuul.project.src_dir }}/test-requirements.txt"
      - "{{ zuul.project.src_dir }}/src/test-requirements.txt"
      - "{{ zuul.project.src_dir }}/build/builds/{{ charm_name }}/test-requirements.txt"
