- hosts: all
  tasks:
    - name: 'force remove Juju machines'
      args:
        executable: /bin/bash
      shell: |
        set -o pipefail
        set -x
        for model in $(juju models | grep zaza- | awk '{gsub(/\*?/,""); print $1}'); do
          if [ "$(juju --version | cut -d. -f 1)" == "2" ];
            juju remove-machine --model $model --force $(seq 0 100)
          else
            juju remove-machine --model $model --force --no-prompt $(seq 0 100)
          fi
        done
      failed_when: false
    - name: 'destroy controller'
      args:
        executable: /bin/bash
      shell: >
        set -x
        if [ "$(juju --version | cut -d. -f 1)" == "2" ];
            timeout 120 juju destroy-controller --destroy-all-models --destroy-storage -y {{ ps6_cloud.region_name }}-{{ ps6_cloud.region_name }}
        else
            timeout 120 juju destroy-controller --destroy-all-models --destroy-storage --no-prompt {{ ps6_cloud.region_name }}-{{ ps6_cloud.region_name }}
        fi
      failed_when: false
    - name: 'kill controller'
      args:
        executable: /bin/bash
      shell: >
        set -x
        if [ "$(juju --version | cut -d. -f 1)" == "2" ];
            juju kill-controller -t 120s -y {{ ps6_cloud.region_name }}-{{ ps6_cloud.region_name }}
        else
            juju kill-controller -t 120s --no-prompt {{ ps6_cloud.region_name }}-{{ ps6_cloud.region_name }}
        fi
      failed_when: false
